### ISSUE TITLE
problems in backdoor_isolation.py

### ISSUE THREAD

**Issue by GuanZihan** [bboylyg/ABL#1]
**#237 line in backdoor_isolation.py**

I thought the parameter here should be "opt" rather than "opt.lr" ?

![image](https://user-images.githubusercontent.com/45278561/145693793-be5dcf43-e30f-404d-8d8b-62de77caf593.png)

**Comment by bboylyg** [comment]
Hi, could you further explain why and what’s the difference between them?

**Comment by xiajun112233** [comment]
Hi, I also have this problem, change the opt.lr to opt in backdoor_isolation.py. And if you want to run the backdoor_unlearning.py, you should add a parser for check_point in config.py.

How to get the 10 backdoor attacks code in this paper?  I find the create_poisoned_data.py is empty.

**Comment by bboylyg** [comment]
Hi, thank you for the kind reminder for the error of `opt`. The implementation for most of the input-space attacks such as BadNets, Trojan, SIG, etc. has already been contained in our `data_loader.py`. As described in the `readme`, not all of the attacks can include in the `data_loader.py` easily, so for the other attacks (e.g. Dynamic, FC) we left the reference code of generating the backdoored model, which is implemented similar to our work.
