### ISSUE TITLE
Links to ImageNet Subset dataset

### ISSUE THREAD

**Issue by zaixizhang** [bboylyg/ABL#4]
Hi, could you kindly share the link to the ImageNet Subset dataset?

**Comment by bboylyg** [comment]
Hi, the link of ImageNet-12 Subset has been released in [Baidu drive](https://pan.baidu.com/s/1LjE6g1cxQ98RZHMWi0tQlA) (pwd: qetk).

**Comment by htwang14** [comment]
Any chance you still remember which 12 classes they are? (I'm trying to reindex them from the original ImageNet.)

**Comment by bboylyg** [comment]
I have already updated the ImageNet-12 subset in [Baidu drive](https://pan.baidu.com/s/1LjE6g1cxQ98RZHMWi0tQlA) (pwd: qetk) and you can download it directly.
