### ISSUE TITLE
whats the parameter ‘pretrained_models_path’？and how it works？

### ISSUE THREAD

**Issue by willu-x** [bboylyg/ABL#5]
in quick_unlearning_demo.py，its set to be ‘opt.checkpoint_root’，but there is no this parameter in opt，how should i use it and how to run this code？

**Comment by bboylyg** [comment]
Hi, 
If you want to have a quick play for the unlearning demo, just need to run the script `python quick_unlearning_demo.py ` directly, where the code has already included the default parameter setup seen [here](https://github.com/bboylyg/ABL/blob/4f42f987156d66ccb54de28641cc81b2932a50bb/quick_unlearning_demo.py#L187).

**Comment by willu-x** [comment]
thank you for your answer ，i have tried `python quick_unlearning_demo.py` directly， but the result is
![image](https://user-images.githubusercontent.com/60807399/178257423-f5891abb-06db-4cc7-be07-e2c106a65029.png)

**Comment by bboylyg** [comment]
Hi,
Thank you for pointing out this naming error. The correct path should be 'opt.isolation_model_root' instead of 'opt.checkpoint_root'. You can change the right name and run code again.
