### ISSUE TITLE
Pre-trained generator model for dynamic attack

### ISSUE THREAD

**Issue by minliu01** [bboylyg/ABL#7]
Hi, Yige!
The implementation of Dynamic Attack seems to have been deleted by the authors. Is there any other way to get the pre-trained generator model?

**Comment by bboylyg** [comment]
HI，
You can download the pretrained `all2one` generator models at [[here](https://drive.google.com/file/d/1b8-1Susq5vk_QXadLS9pH45F68z3FAOS/view?usp=sharing)].

**Comment by minliu01** [comment]
Thanks!
